name: CD - Result Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'result/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push container
        uses: docker/build-push-action@v5
        with:
          context: result
          push: true
          tags: |
            ${{ secrets.REGISTRY }}/result:${{ github.sha }}
            ${{ secrets.REGISTRY }}/result:latest
  
  update-manifests:
    needs: build-and-push
    uses: ./.github/workflows/update-k8s-manifests.yaml
    with:
      service: result
      image-tag: ${{ github.sha }}
    secrets:
      MANIFESTS_REPO_PAT: ${{ secrets.MANIFESTS_REPO_PAT }}
      REGISTRY: ${{ secrets.REGISTRY }}
